server:
    port: 8301

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    #git仓库的地址
                    uri: https://github.com/YeJR1993/butler-springcloud.git
                    # 配置仓库路径，这里是文件夹搜索路径
                    searchPaths: cloud-config
                    # git仓库的用户名和密码，如果是public仓库，可以不写
                    username: YeJR1993
                    password: ye13615248452
                    # 指定分支，不指定默认是master
                    default-label: master