server:
    port: 8082

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
    application:
        name: config-server
    rabbitmq:
        host: 192.168.56.101
        port: 5672
        username: guest
        password: guest
    cloud:
        config:
            server:
                git:
                    #git仓库的地址, 由于git的网络原因，这里使用gitee
                    uri: https://gitee.com/yejiarong/butler-springcloud.git
                    # 配置仓库路径，这里是文件夹搜索路径
                    searchPaths: cloud-config
                    # 默认分支
                    default-label: master

eureka:
    instance:
        hostname: 127.0.0.1
        # 心跳检测检测与续约时间
        lease-renewal-interval-in-seconds: 3   # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
        lease-expiration-duration-in-seconds: 5 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    client:
        # 注册中心地址
        service-url:
            defaultZone: http://127.0.0.1:8081/eureka/

# 手动刷新配置, POST http://127.0.0.1:18082/actuator/refresh 手动提交刷新
management:
    endpoints:
        web:
            # 用于指定actuator的URL路径 默认 /actuator
            # base-path: /actuator
            # 指定监控项。默认开启了health、info。这里加入了refresh
            exposure:
                include: bus-refresh,health,info # 2.X 版本的配置方式。默认只有health,info，这里需要将refresh添加上【手动刷新使用的是refresh，使用消息总线则是bus-refresh】
    endpoint:
        health:
            # 用于展示监控项详细信息，默认不展示
            show-details: always
    server: # 指定actuator端口。如果不指定则与系统服务端口一致。建议修改
        port: 18082
