server:
    port: 8082

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    #git仓库的地址, 由于git的网络原因，这里使用gitee
                    uri: https://gitee.com/yejiarong/butler-springcloud.git
                    # 配置仓库路径，这里是文件夹搜索路径
                    searchPaths: cloud-config
                    # 默认分支
                    default-label: master

eureka:
    instance:
        hostname: 127.0.0.1
        # 心跳检测检测与续约时间
        lease-renewal-interval-in-seconds: 3   # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
        lease-expiration-duration-in-seconds: 5 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    client:
        # 注册中心地址
        service-url:
            defaultZone: http://127.0.0.1:8081/eureka/
