server:
    port: 8082

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    #git仓库的地址, 由于git的网络原因，这里使用gitee
                    uri: https://gitee.com/yejiarong/butler-springcloud.git
                    # 配置仓库路径，这里是文件夹搜索路径
                    searchPaths: cloud-config
                    # 默认分支
                    default-label: master